### ISSUE TITLE
SAN's & Prices not loaded in $client->certificate()->all();

### ISSUE THREAD

**Issue by dbijman** [xolphin/xolphin-api-php#10]
When using the API and code in the examples the output of the subjectAlternativeNames field and also the product => prices array is empty
![image](https://user-images.githubusercontent.com/7191068/38872566-dfd75726-4253-11e8-996d-903cb001e0c2.png)

**Comment by ghost** [comment]
Thanks for your suggestion. 
We will update our API in the near future and add subjectAlternativeNames to the certificate object in the API for the `/certificates`. 

Regarding the prices, the prices in the product object are not displayed because these are irrelevant for the response. You could use the method `$client->support()->product(<id>)` to get the actual product prices.

**Comment by gjportegies** [comment]
Hi @XolphinBart any progress on adding the subjectAlternativeNames to this API call? At this point I've to do separate request for every certificate to get those.

**Comment by XolphinSam** [comment]
subjectAlternativeNames is now available on the /v1/certificates endpoint
