### ISSUE TITLE
Awaiting release v3.0.5

### ISSUE THREAD

**Issue by robbinjanssen** [xolphin/xolphin-api-php#41]
Currently some of our API calls to the xolphin are not working because of the new representative fields, the 3.0.4 release contains return types bugs which have been fixed in master, however these have not yet been released. Please release this so we can update our package and code.

**Comment by oriboio** [comment]
Still waiting

**Comment by robbinjanssen** [comment]
![](https://media1.giphy.com/media/QBd2kLB5qDmysEXre9/giphy.gif?cid=6c09b952ht7pv8alwbx7c6g3cf3pv7gmres8rydy6frhcrve&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by dvdheiden** [comment]
Seems Xolphin (actually Sectigo) doesn't care about supporting this official package as it currently is in a broken non-working state 😞 

You could change this in your `composer.json`:

```
"xolphin/xolphin-api-php": "dev-master",
```

Which will use master and should fix it for now. Be sure to change it back as soon as Xolphin releases a new version.

**Comment by mvdgeijn** [comment]
Request for a reissue of a certificate is also not working in the dev-master: 400 Bad Request. dcv invalid value. Time to change our SSL provider.

**Comment by tomsommer** [comment]
Xolphin is being shut down anyway, so why even bother?

**Comment by WilliamDEdwards** [comment]
From our Partner Account Manager at Sectigo:

> To give you some background, Xolphin was acquired by Sectigo in 2020. After a few months, Sectigo decided to change its strategy and most of Xolphin's employees were considered redundant, which led to a considerable downsizing. As a result, we have lacked customer support over the last few years.
> 
> Now the situation is changing, we are now hiring more and more people so the situation should go in the right direction. To give you concrete updates we’ve just hired a new person that will be in charge of the customer success Bas Hureau-Haitjema, you will probably hear from him in the future.

**Comment by ohalessl247** [comment]
Hi Gentleman,
Firstly, I apologise for the delays in getting back to this GitHub issue thread. We are reviewing our communication channels and monitoring processes. We recommend reaching out for support of the API and official SDKs through [https://www.xolphin.com/contact](https://www.xolphin.com/contact)

Xolphin is committed to delivering world-class trust-based certificates. Over the last few months, our underlying systems have been aligned to Sectigo’s to provide faster issuance and improved validation tools. Xolphin is not being closed, and we look to take on feedback from our partners.

@mvdgeijn -   The issue surrounding an outage “400 Bad Request. dcv invalid value”, has since been rectified, I again apologies for any inconvenience caused. 

@robbinjanssen - The reported issues around types has been added to a tag  and  can be found here:

[https://github.com/xolphin/xolphin-api-php/tree/v3.0.5](https://github.com/xolphin/xolphin-api-php/tree/v3.0.5)

@WilliamDEdwards -  thank you for your pull request.

Representative fields can be set using the functions found in:
[https://github.com/xolphin/xolphin-api-php/blob/master/src/Requests/CertificateRequest.php#L379](https://github.com/xolphin/xolphin-api-php/blob/master/src/Requests/CertificateRequest.php#L379)

For more information around upgrading your API follow our guide here:
[https://www.xolphin.com/downloads/Changes-affecting-Xolphin-Customers-V1.1%203.pdf](https://www.xolphin.com/downloads/Changes-affecting-Xolphin-Customers-V1.1%203.pdf)

**Comment by WilliamDEdwards** [comment]
> We recommend reaching out for support of the API and official SDKs through https://www.xolphin.com/contact

Messages via the form and email aren't replied to. Phone support is useless (outsourced to India). So how do you suggest we file urgent issues?

**Comment by ohalessl247** [comment]
Hi @WilliamDEdwards,
I understand your frustration. Please contact us using the support form with your company details, and we will work with your account manager to correct what you are experiencing appropriately.

**Comment by WilliamDEdwards** [comment]
Hi @ohalessl247. Are you saying that the support form is replied to nowadays?

**Comment by erickramernl** [comment]
Hi William, if in the support form it is noted that is for API support, it will be rerouted to the Sectigo development team now.

**Comment by robbinjanssen** [comment]
I'll close this issue as my problem has been resolved. 

However I agree with all the comments above about the lack of communication. My 2 cents; it feels like since sectigo has taken over, all we get is fatter bills and worse support. But Github is not the place for this.

Thanks for release v3.0.5

**Comment by WilliamDEdwards** [comment]
> Hi William, if in the support form it is noted that is for API support, it will be rerouted to the Sectigo development team now.

My question from several days ago, asked via the contact form, has not been answered.

**Comment by WilliamDEdwards** [comment]
> > Hi William, if in the support form it is noted that is for API support, it will be rerouted to the Sectigo development team now.
> 
> My question from several days ago, asked via the contact form, has not been answered.

The question I asked **before** May 10th, was answered on May 15th, and of course the answer is useless.

The 'Partner Account Manager' also stopped replying 22 days ago. And this conversation is not being monitored. 

Interesting way of "working with your account manager to correct what you are experiencing appropriately"!

**Comment by WilliamDEdwards** [comment]
> > > Hi William, if in the support form it is noted that is for API support, it will be rerouted to the Sectigo development team now.
> > 
> > 
> > My question from several days ago, asked via the contact form, has not been answered.
> 
> The question I asked **before** May 10th, was answered on May 15th, and of course the answer is useless.
> 
> The 'Partner Account Manager' also stopped replying 22 days ago. And this conversation is not being monitored.
> 
> Interesting way of "working with your account manager to correct what you are experiencing appropriately"!

Still no reply from the partner manager. No reply here on GitHub. Support takes at least 10 days to reply to every message, with patently false answers of course. 

@erickramernl @ohalessl247 How's the "reviewing communication channels and monitoring processes" going?
